# jupyterlab-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: jupyterlab
  namespace: ai-workloads
  labels:
    app: jupyterlab
spec:
  type: NodePort
  selector:
    app: jupyterlab
  ports:
    - name: http
      port: 8888
      targetPort: 8888
      nodePort: 30088  # Choose a port within the 30000-32767 range
    - name: tcp
      port: 8080
      targetPort: 8080