apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
  namespace: ai-workloads
provisioner: rancher.io/local-path
parameters:
  type: local
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: false
