apiVersion: apps/v1
kind: Deployment
metadata:
  name: weaviate
  namespace: ai-workloads
  labels:
    app: weaviate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weaviate
  template:
    metadata:
      labels:
        app: weaviate
    spec:
      containers:
        - name: weaviate
          image: semitechnologies/weaviate:1.27.0
          imagePullPolicy: IfNotPresent
          command: ["/bin/weaviate"]
          args:
            - '--host'
            - '0.0.0.0'
            - '--port'
            - '8080'
            - '--scheme'
            - 'http'
            - '--config-file'
            - '/weaviate-config/conf.yaml'
            - '--read-timeout=60s'
            - '--write-timeout=60s'
          ports:
            - containerPort: 8080
            - containerPort: 50051 
          env:
            - name: QUERY_DEFAULTS_LIMIT
              value: "100"
            - name: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
              value: "true"
            - name: PERSISTENCE_DATA_PATH
              value: "/var/lib/weaviate"
            - name: CLUSTER_GOSSIP_BIND_PORT
              value: "7000"
            - name: CLUSTER_DATA_BIND_PORT
              value: "7001"
            - name: RAFT_BOOTSTRAP_TIMEOUT
              value: "600"
            - name: GOGC
              value: "100"
            # Add additional environment variables if needed
          volumeMounts:
            - name: weaviate-data
              mountPath: /var/lib/weaviate
          livenessProbe:
            httpGet:
              path: /v1/.well-known/live
              port: 8080
            initialDelaySeconds: 900
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /v1/.well-known/ready
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
              nvidia.com/gpu: 1
            limits:
              cpu: "8"
              memory: "32Gi"
              nvidia.com/gpu: 1
      volumes:
        - name: weaviate-data
          persistentVolumeClaim:
            claimName: weaviate-pvc

